export const COLORS = {
  primary: '#E91E8C',
  primaryLight: '#FF69B4',
  primaryDark: '#C2185B',
  secondary: '#9C27B0',
  accent: '#FF4081',
  white: '#FFFFFF',
  black: '#000000',
  gray: '#9E9E9E',
  lightGray: '#F5F5F5',
  darkGray: '#424242',
  background: '#FAFAFA',
  error: '#F44336',
  success: '#4CAF50',
  warning: '#FF9800',
  text: '#212121',
  textSecondary: '#757575',
};

export const FONTS = {
  regular: 'System',
  medium: 'System',
  bold: 'System',
  light: 'System',
};

export const SIZES = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
  borderRadius: 12,
  cardRadius: 16,
};

export const MOCK_TUTORIALS = [
  {
    id: '1',
    title: 'Natural Everyday Makeup',
    description: 'Learn how to create a flawless natural look for everyday wear',
    category: 'makeup' as const,
    difficulty: 'beginner' as const,
    duration: 15,
    thumbnail: 'https://picsum.photos/seed/makeup1/400/300',
    steps: [],
    tags: ['natural', 'everyday', 'beginner'],
    likes: 1245,
    author: 'Beauty Expert',
  },
  {
    id: '2',
    title: 'Glowing Skin Routine',
    description: 'Get that perfect glass skin effect with this skincare routine',
    category: 'skincare' as const,
    difficulty: 'beginner' as const,
    duration: 20,
    thumbnail: 'https://picsum.photos/seed/skincare1/400/300',
    steps: [],
    tags: ['skincare', 'glow', 'routine'],
    likes: 2389,
    author: 'Skin Specialist',
  },
  {
    id: '3',
    title: 'Beachy Waves Hairstyle',
    description: 'Create effortless beachy waves that last all day',
    category: 'hairstyle' as const,
    difficulty: 'intermediate' as const,
    duration: 25,
    thumbnail: 'https://picsum.photos/seed/hair1/400/300',
    steps: [],
    tags: ['waves', 'beach', 'summer'],
    likes: 987,
    author: 'Hair Stylist Pro',
  },
  {
    id: '4',
    title: 'Bold Evening Look',
    description: 'Transform your look for a night out with this bold makeup tutorial',
    category: 'makeup' as const,
    difficulty: 'advanced' as const,
    duration: 35,
    thumbnail: 'https://picsum.photos/seed/makeup2/400/300',
    steps: [],
    tags: ['evening', 'bold', 'glam'],
    likes: 3421,
    author: 'MUA Professional',
  },
];

export const MOCK_PRODUCTS = [
  {
    id: 'p1',
    name: 'Hydrating Foundation SPF 30',
    brand: 'Lumière',
    category: 'foundation',
    price: 42.99,
    rating: 4.5,
    reviewCount: 2847,
    description: 'Full coverage foundation with SPF 30 protection and 24-hour hydration',
    image: 'https://picsum.photos/seed/product1/300/300',
    tags: ['foundation', 'SPF', 'hydrating'],
    suitableFor: ['dry', 'combination'],
  },
  {
    id: 'p2',
    name: 'Rose Gold Highlighter Palette',
    brand: 'Glow Co',
    category: 'highlighter',
    price: 28.50,
    rating: 4.8,
    reviewCount: 1562,
    description: 'Multi-shade highlighter palette for a radiant, lit-from-within glow',
    image: 'https://picsum.photos/seed/product2/300/300',
    tags: ['highlighter', 'glow', 'palette'],
    suitableFor: ['all'],
  },
  {
    id: 'p3',
    name: 'Vitamin C Brightening Serum',
    brand: 'SkinLab',
    category: 'serum',
    price: 65.00,
    rating: 4.7,
    reviewCount: 4123,
    description: 'Advanced vitamin C formula to brighten and even skin tone',
    image: 'https://picsum.photos/seed/product3/300/300',
    tags: ['serum', 'vitamin C', 'brightening'],
    suitableFor: ['all', 'dull'],
  },
  {
    id: 'p4',
    name: 'Curl Defining Cream',
    brand: 'CurlPerfect',
    category: 'hair',
    price: 22.00,
    rating: 4.4,
    reviewCount: 892,
    description: 'Define and enhance natural curls with this nourishing curl cream',
    image: 'https://picsum.photos/seed/product4/300/300',
    tags: ['curly hair', 'curl cream', 'moisturizing'],
    suitableFor: ['curly', 'wavy'],
  },
];

export const MOCK_SALONS = [
  {
    id: 's1',
    name: 'Bella Vista Salon',
    address: 'Via Roma 15, Milano',
    rating: 4.8,
    reviewCount: 324,
    image: 'https://picsum.photos/seed/salon1/400/300',
    openHours: '09:00 - 20:00',
    phone: '+39 02 1234567',
    services: [
      { id: 'sv1', name: 'Haircut & Style', duration: 60, price: 45, category: 'hair' },
      { id: 'sv2', name: 'Color Treatment', duration: 120, price: 95, category: 'hair' },
      { id: 'sv3', name: 'Facial Treatment', duration: 60, price: 75, category: 'skin' },
      { id: 'sv4', name: 'Manicure & Pedicure', duration: 90, price: 65, category: 'nails' },
    ],
  },
  {
    id: 's2',
    name: 'Glamour Studio',
    address: 'Corso Buenos Aires 22, Milano',
    rating: 4.6,
    reviewCount: 198,
    image: 'https://picsum.photos/seed/salon2/400/300',
    openHours: '10:00 - 21:00',
    phone: '+39 02 9876543',
    services: [
      { id: 'sv5', name: 'Blowout & Style', duration: 45, price: 35, category: 'hair' },
      { id: 'sv6', name: 'Keratin Treatment', duration: 180, price: 150, category: 'hair' },
      { id: 'sv7', name: 'Eyebrow Shaping', duration: 30, price: 25, category: 'brow' },
      { id: 'sv8', name: 'Lash Extensions', duration: 90, price: 85, category: 'lash' },
    ],
  },
];

export const MOCK_POSTS = [
  {
    id: 'post1',
    userId: 'u1',
    userName: 'Sofia Rossi',
    userAvatar: undefined,
    content: 'Just tried this amazing new skincare routine and my skin is glowing! ✨ #skincare #glow #beautyRoutine',
    images: [],
    likes: 142,
    comments: 23,
    tags: ['skincare', 'glow', 'beautyRoutine'],
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    isLiked: false,
  },
  {
    id: 'post2',
    userId: 'u2',
    userName: 'Laura Bianchi',
    userAvatar: undefined,
    content: 'My go-to summer makeup look 💄 Light, fresh and perfect for hot days! #summermakeup #naturalbeauty',
    images: [],
    likes: 289,
    comments: 45,
    tags: ['summermakeup', 'naturalbeauty'],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    isLiked: true,
  },
  {
    id: 'post3',
    userId: 'u3',
    userName: 'Emma Greco',
    userAvatar: undefined,
    content: 'Finally found the perfect curl cream for my 3C curls! 💇‍♀️ No more frizz! #curlyhair #haircare #curlygirl',
    images: [],
    likes: 523,
    comments: 87,
    tags: ['curlyhair', 'haircare', 'curlygirl'],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    isLiked: false,
  },
];

export const MOCK_APPOINTMENTS = [
  {
    id: 'a1',
    salonId: 's1',
    salonName: 'Bella Vista Salon',
    serviceId: 'sv1',
    serviceName: 'Haircut & Style',
    date: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    time: '14:00',
    status: 'confirmed' as const,
    price: 45,
  },
  {
    id: 'a2',
    salonId: 's2',
    salonName: 'Glamour Studio',
    serviceId: 'sv8',
    serviceName: 'Lash Extensions',
    date: new Date(Date.now() - 604800000).toISOString().split('T')[0],
    time: '11:00',
    status: 'completed' as const,
    price: 85,
  },
];